apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-user-service
  namespace: go-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-user-service
  template:
    metadata:
      labels:
        app: grpc-user-service
    spec:
      containers:
      - name: grpc-server
        image: grpc-server:429c8f7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-user-service
  namespace: go-grpc
spec:
  selector:
    app: grpc-user-service
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051